app/login/models.py
import os

from cryptography.fernet import Fernet
from werkzeug.security import generate_password_hash, check_password_hash

from app import db


class Usuario(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(20), unique=True,nullable=False)
    password = db.Column(db.String())
    dni = db.Column(db.String(10),nullable=False,unique=True)
    nombre = db.Column(db.String(20),nullable=False)
    apellidos = db.Column(db.String(50),nullable=False)
    telefono = db.Column(db.String(50),nullable=False)
    telefonoAlternativo = db.Column(db.String(50),nullable=False)
    email = db.Column(db.String(50),nullable=False)
    direccion = db.Column(db.String(50),nullable=False)
    def create(self):
        try:
            db.session.add(self)
            db.session.commit()
        except:
            raise

    def update(self):
        try:
            db.session.commit()
        except:
            raise

    @staticmethod
    def get_by_id(id):
        return Usuario.query.get(id)

    @staticmethod
    def get_by_username(username):
        return Usuario.query.filter_by(username=username).first()


    def set_password(self, password):
        # self.login = generate_password_hash(login, method='pbkdf2:sha512')
        method = "pbkdf2:sha256:260000"
        # method = "plain"
        # method = "pbkdf2:sha512:1000000"
        self.password = generate_password_hash(password,method=method) #Por defecto sha256
        # self.login = login.split("$", 1)[1]


    def check_password(self, password):
        # passHash = 'pbkdf2:sha256:260000$' + self.login
        return check_password_hash(self.password, password)

app/login/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField, PasswordField
from flask_wtf.file import FileRequired, FileAllowed, FileField
from wtforms.validators import DataRequired, Length, ValidationError


class LoginForm(FlaskForm):
    username = StringField(label="Nombre de usuario", validators=[
        DataRequired(message="El nombre de usuario es obligatorio"),
        Length(max=20, message="El nombre de usuario no puede ser superior a 20 caracteres")
    ])

    password = PasswordField(label="Contraseña", validators=[
        DataRequired(message="La contraseña es obligatoria"),
        Length(min=8, message="La contraseña no puede ser inferior a 8 caracteres")
    ])


class UsuarioForm(FlaskForm):

    username = StringField(label="Nombre de usuario", validators=[
        DataRequired(message="El nombre de usuario es obligatorio"),
        Length(max=20, message="El nombre de usuario no puede ser superior a 20 caracteres")
    ])

    password = PasswordField(label="Contraseña", validators=[
        DataRequired(message="La contraseña es obligatoria"),
        Length(min=8, message="La contraseña no puede ser inferior a 8 caracteres")
    ])
    passwordRepeat = PasswordField(label="Repita la contraseña", validators=[
        DataRequired(message="La repetición de la contraseña es obligatoria"),
        Length(min=8, message="La contraseña no puede ser inferior a 8 caracteres")
    ])

    dni = StringField(label="DNI", validators=[
        DataRequired(message="El dni es obligatorio"),
        Length(max=10, message="El dni no puede ser superior a 10 caracteres")
        ])

    nombre = StringField(label="Nombre", validators=[
        DataRequired(message="El nombre es obligatorio"),
        Length(max=20, message="El nombre no puede ser superior a 10 caracteres")
        ])

    apellidos = StringField(label="Apellidos", validators=[
        DataRequired(message="Los apellidos son obligatorio"),
        Length(max=50, message="Los apellidos no pueden superar los 50 caracteres")
        ])
    telefono = StringField(label="Telefono", validators=[
        DataRequired(message="El telfono es obligatorio"),
        Length(max=9, min=9, message="Debe tener 9 digitos")
        ])
    telefonoAlternativo = StringField(label="Telefono alternativo", validators=[
        DataRequired(message="El telfono es obligatorio"),
        Length(max=9, min=9, message="Debe tener 9 digitos")
    ])
    email = StringField(label="e-mail", validators=[
        DataRequired(message="Debe rellenar el e-mail")
    ])
    direccion = StringField(label="Dirección", validators=[
        DataRequired(message="Debe rellenar ete campo")
    ])
    # submit = SubmitField(label="Dar de alta")

    def validate_password(form,field):
        if str(field.data).isdigit():
            raise ValidationError("La contraseña no pueden ser solo dígitos")
        if field.data != form.passwordRepeat.data:
            raise ValidationError("No coinciden las contraseñas")

    def validate_passwordRepeat(form, field):
        if field.data != form.password.data:
            raise ValidationError("No coinciden las contraseñas")

app/__init__.py
from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
app.secret_key = "ClaveSecreta"
app.config['SQLALCHEMY_DATABASE_URI'] = "postgresql://postgres:123456@localhost:5432/dbLingo"
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
db = SQLAlchemy(app)
migrate = Migrate(app, db)


from .login import password

def create_app():
    app.register_blueprint(password)
    return  app

app/login/__init__.py
from flask import Blueprint
password = Blueprint('login', __name__, template_folder='templates', static_folder='static')

from . import routes

app/login/routes.py
from flask import render_template, request, redirect, url_for

import app
from . import password
from .models import Usuario
from .forms import UsuarioForm, LoginForm
from .auxiliar import encriptar_password, desencriptar_password
from .. import db

PEEPER = "ClaveSecretaPeeper"


@password.route('/')
def index():  # put application's code here
    return render_template('index.html')

@password.route("/welcome/")
def welcome():
    return render_template("welcome.html")

@password.route("/hasheadapeeper/", methods=["GET","POST"])
def hasheadapeeper():
    error = ""
    form = UsuarioForm(request.form)
    return render_template("hasheadapeeper.html", form=form, error=error)

@password.route("/loginhasheadopeeper/", methods=["GET","POST"])
def loginhasheadopeeper():
    error = ""
    form = LoginForm(request.form)
    return render_template("loginhasheadopeeper.html", form=form, error=error)

app/templates/base/_helpers.html
{% macro generarForm(form) %}
    {{ form.csrf_token() }}
    {% for field in form %}
        <div class="mb-3 mt-3">
            {% if field.type != 'CSRFTokenField' and field.type != "HiddenField"  %}
                {{ field.label(class="form-label") }}
                {{ field(class="form-control") }}
                <ul class="text-danger">
                {% for error in field.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
                </ul>
            {% else %}
                {{ field() }}
            {% endif %}
        </div>
    {% endfor %}
{% endmacro %}

app/templates/base/_menu.html
{% macro show_menu() %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ url_for('login.index') }}">Lingo</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{{ url_for('login.index') }}">Home</a>
        </li>
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">Iniciar Sesion</a>
              <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{{ url_for('login.hasheadapeeper') }}">Registro</a></li>
                  <li><a class="dropdown-item" href="{{ url_for('login.loginhasheadopeeper') }}">Login</a></li>
              </ul>
          </li>
      </ul>
    </div>
  </div>
</nav>
{% endmacro %}

app/templates/base/_menuPrincipal.html
{% macro show_menuPrincipal() %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('login.index') }}">Lingo</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{{ url_for('login.loginhasheadopeeper') }}">Administración</a>
            </li>
          </ul>
        </div>
    </div>
</nav>
{% endmacro %}

app/templates/base/base.html
<!DOCTYPE html>
{% from "base/_menu.html" import show_menu %}
{% from "base/_menuPrincipal.html" import show_menuPrincipal %}
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <link href="{{ url_for('static',filename='css/bootstrap/bootstrap.css') }}" rel="stylesheet">
        <script src="{{ url_for('static',filename='js/bootstrap/bootstrap.min.js') }}"></script>
        <title>{% block titulo %}Lingo{% endblock %}</title>
    </head>
    <body>
        <header>
            {{ show_menuPrincipal() }}
            <img class="img-fluid", src="{{ url_for('static', filename="img/baner_Lingo.jpg") }}">
        </header>
        <div class="container">
            <main role="main" class="pb-3">
            {% block contenido %}
            </main>
            {% endblock %}
            <footer class="border-top footer text-muted">
                <div class="container">
                    Lingo English School
                </div>
            </footer>
        </div>
    </body>
</html>